project:
  type: website
  resources: static

website:
  title: "Ron Yurko"
  site-url: "http://www.stat.cmu.edu/~ryurko/"
  navbar:
    right:
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: static/cv.pdf
      - icon: github
        href: https://github.com/ryurko
      - icon: twitter
        href: https://twitter.com/Stat_Ron

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

