---
title: "Publications and Preprints"
---

### 2025

+ Quang Nguyen  and __Ronald Yurko__. "A multilevel model with heterogeneous variances for snap timing in the National Football League," _Journal of the Royal Statistical Society Series A: Statistics in Society_, 2025. [(link)](https://academic.oup.com/jrsssa/advance-article/doi/10.1093/jrsssa/qnaf185/8315856?login=false)

+ Zach Branson, Monica Paz Parra, and __Ronald Yurko__. "The landscape of college-level data visualization courses, and the benefits of incorporating statistical thinking," _Journal of Statistics and Data Science Education_, 2025. [(link)](https://www.tandfonline.com/doi/full/10.1080/26939169.2025.2537049)

+ Quang Nguyen  and __Ronald Yurko__. "A bayesian circular mixed-effects model for explaining variability in directional movement in american football," _arXiv preprint_, 2025. [(preprint)](https://arxiv.org/abs/2507.06122)

+ Scott Powers  and __Ronald Yurko__. "Swinging, fast and slow: Interpreting variation in baseball swing tracking metrics," _arXiv preprint_, 2025. [(preprint)](https://arxiv.org/abs/2507.01238)

+ Ryan Brill, __Ronald Yurko__, and Abraham J Wyner. "Exploring the difficulty of estimating win probability: a simulation study," _Journal of Quantitative Analysis in Sports_, 2025. [(link)](https://www.degruyterbrill.com/document/doi/10.1515/jqas-2024-0130/html)

+ Ryan Brill, __Ronald Yurko__, and Abraham J Wyner. "Analytics, have some humility: a statistical view of fourth-down decision making," _The American Statistician_, 2025. [(link)](https://www.tandfonline.com/doi/abs/10.1080/00031305.2025.2475801)

+ Alex Reinhart, Ben Markey, Michael Laudenbach, Kachatad Pantusen, __Ronald Yurko__, Gordon Weinberg, and David Brown. "Do LLMs write like humans? Variation in grammatical and rhetorical styles," _Proceedings of the National Academy of Sciences_, 2025. [(link)](https://www.pnas.org/doi/10.1073/pnas.2422455122)

+ Quang Nguyen, Ruitong Jiang, Meg Ellingwood, and __Ronald Yurko__. "Fractional tackles: Leveraging player tracking data for within-play tackling evaluation in american football," _Scientific Reports_, 2025. [(link)](https://www.nature.com/articles/s41598-025-85993-1)


### 2024

+ __Ronald Yurko__, Quang Nguyen, and Konstantinos Pelechrinis. "NFL Ghosts: A framework for evaluating defender positioning with conditional density estimation," _arXiv preprint_, 2024. [(preprint)](https://arxiv.org/abs/2406.17220)

+ Adriana Gonzalez Sanchez, Sierra Martinez, __Ronald Yurko__, and Ryan Elmore. "Does Icing the Field Goal Kicker Work in the National Football League?", _CHANCE_, 2024. [(link)](https://www.tandfonline.com/doi/pdf/10.1080/09332480.2024.2415841?casa_token=gDYSucFwk4oAAAAA:OK5ZvoaS04aayEcMeWM-xjIkDk6G1iXLfZJQyZNhLon9DBl69K_BO5Sx2bbKoZFaPXE1k8F-9iO-_g)

+ Yujin Kim, Minwoo Jeong, In Gyeong Koh, Chanhee Kim, Hyeji Lee, Jae Hyun Kim, __Ronald Yurko__, Il Bin Kim, Jeongbin Park, Donna M Werling, Stephan J Sanders, and Joon-Yong. "CWAS-Plus: estimating category-wide association of rare noncoding variation from whole-genome sequencing data with cell-type-specific functional data," _Briefings in Bioinformatics_, 2024. [(link)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11224609/)


### 2023

+ Quang Nguyen, __Ronald Yurko__, and Gregory J Matthews. "Here Comes the STRAIN: Analyzing Defensive Pass Rush in American Football with Player Tracking Data," _The American Statistician_, 2023. [(link)](https://www.tandfonline.com/doi/full/10.1080/00031305.2023.2242442)

### 2021

+ __Ronald Yurko__, Kathryn Roeder, Bernie Devlin, and Max G'Sell. "An approach to gene-based testing accounting for dependence of tests among nearby genes," _Briefings in Bioinformatics_, 2021. [(link)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8575037/)

+ __Ronald Yurko__, Kathryn Roeder, Bernie Devlin, and Max G'Sell. "H-MAGMA, inheriting a shaky statistical foundation, yields excess false positives," _Annals of Human Genetics_, 2021. [(link](https://onlinelibrary.wiley.com/doi/10.1111/ahg.12412), [preprint)](https://www.biorxiv.org/content/10.1101/2020.08.20.260224v1)

+ Riccardo Fogliato, Natalia L Oliveira, and __Ronald Yurko__. "TRAP: a predictive framework forthe Assessment of Performance in Trail Running," _Journal of Quantitative Analysis in Sports_, 2021. [(link](https://www.degruyter.com/document/doi/10.1515/jqas-2020-0013/html?lang=en), [preprint)](https://arxiv.org/abs/2002.01328)

### 2020

+ __Ronald Yurko__, Francesca Matano, Lee F Richardson, Nicholas Granered, Taylor Pospisil, Konstantinos Pelechrinis, and Samuel L Ventura. "Going deep: models for continuous-time within-play valuation of game outcomes in american football with tracking data," _Journal of Quantitative Analysis in Sports_, 2020. [(link)](https://www.degruyter.com/document/doi/10.1515/jqas-2019-0056/html?lang=en)

+ __Ronald Yurko__, Max G’Sell, Kathryn Roeder, and Bernie Devlin. "A selective inference approach for false discovery rate control using multiomics covariates yields insights into disease risk," _Proceedings of the National Academy of Sciences_, 2020. [(link)](https://www.pnas.org/doi/abs/10.1073/pnas.1918862117)

+ Sarah Mallepalle, __Ronald Yurko__, Konstantinos Pelechrinis, and Samuel L Ventura. "Extracting NFL tracking data from images to evaluate quarterbacks and pass defenses," _Journal of Quantitative
Analysis in Sports_, 2020. [(link)](https://www.degruyter.com/document/doi/10.1515/jqas-2019-0052/html?lang=en), [preprint](https://arxiv.org/abs/1906.03339)

+ Rishav Dutta, __Ronald Yurko__, and Samuel L Ventura. "Unsupervised methods for identifying pass coverage among defensive backs with nfl player tracking data," _Journal of Quantitative
Analysis in Sports_, 2020. [(link](https://www.degruyter.com/document/doi/10.1515/jqas-2020-0017/html?lang=en), [preprint)](https://arxiv.org/abs/1906.11373)

### 2019

+ __Ronald Yurko__, Samuel Ventura, and Maksim Horowitz. "nflWAR: a reproducible method for offensive player evaluation in football," _Journal of Quantitative Analysis in Sports_, 2019. [(link](https://www.degruyter.com/document/doi/10.1515/jqas-2018-0010/html?lang=en), [extended edition)](https://arxiv.org/abs/1802.00998)

+ Konstantinos Pelechrinis, __Ronald Yurko__, and Sam Ventura. "Reducing Concussions in the NFL: A Data-Driven Approach," _CHANCE_, 2019. [(link)](https://chance.amstat.org/2019/11/reducing-concussions/)

